### PR TITLE
Use DocBlock

### PR DESCRIPTION
**Pull request by zonuexe**
This notation fits more processing systems.

### CODE REVIEW

**Review by tanakahisateru — COMMENTED** [review]
Isn't Eclipse PDT compatible style?

**Comment by tanakahisateru** [comment]
@zonuexe ls this answer too old? https://stackoverflow.com/questions/14115654/annotating-a-local-variable-in-php Let me know if so or not plz.

**Comment by zonuexe** [comment]
@tanakahisateru 
I'm sorry. This best answer seems to be correct for me.
(Since `ReflectVariable` class does not exist, local variables do not require `/**` even in PHP specification.)

In addition, I was misunderstanding [Phan](https://github.com/etsy/phan)'s behavior.
Phan does not accept annotations for local variables. (I'm using Phan 0.9.2-dev https://github.com/etsy/phan/commit/2e88cf4fc2b4ba30f47752ce098dc4d5583958df)

Therefore, I have no positive reason to write annotations in the DocComment format for local variables.

**Comment by tanakahisateru** [comment]
@zonuexe All bad things are csused by Eclipse and PSR-5 ☹️

**Pull request closed without merging**
